{"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/_pythonstring\/pyexception\/attributeerror(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"attributeError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","externalID":"s:13_PythonString11PyExceptionO14attributeErroryACSScACmF","role":"symbol","title":"PyException.attributeError(_:)","modules":[{"name":"_PythonString"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributeError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/attributeError(_:)","interfaceLanguage":"swift"},"references":{"doc://com.swallow.documentation._PythonString/documentation/_PythonString":{"abstract":[],"role":"collection","title":"_PythonString","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString","url":"\/documentation\/_pythonstring","type":"topic","kind":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/attributeError(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"attributeError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"PyException.attributeError(_:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/attributeError(_:)","url":"\/documentation\/_pythonstring\/pyexception\/attributeerror(_:)","role":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException":{"title":"PyException","navigatorTitle":[{"text":"PyException","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/_pythonstring\/pyexception","kind":"symbol","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PyException","kind":"identifier"}]}}}