{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/_pythonstring\/pyexception\/customstringconvertible-implementations"]}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/CustomStringConvertible-Implementations"},"metadata":{"role":"collectionGroup","modules":[{"name":"_PythonString"}],"roleHeading":"API Collection","title":"CustomStringConvertible Implementations"},"sections":[],"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/description"],"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.swallow.documentation._PythonString/documentation/_PythonString":{"abstract":[],"role":"collection","title":"_PythonString","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString","url":"\/documentation\/_pythonstring","type":"topic","kind":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException":{"title":"PyException","navigatorTitle":[{"text":"PyException","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/_pythonstring\/pyexception","kind":"symbol","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PyException","kind":"identifier"}]},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/description":{"url":"\/documentation\/_pythonstring\/pyexception\/description","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","kind":"symbol","title":"description"}}}