{"identifier":{"url":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/exception(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/_pythonstring\/pyexception\/exception(_:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"PyException.exception(_:)","modules":[{"name":"_PythonString"}],"role":"symbol","symbolKind":"case","externalID":"s:13_PythonString11PyExceptionO9exceptionyACSScACmF","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exception","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exception"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/exception(_:)":{"identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/exception(_:)","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exception"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/_pythonstring\/pyexception\/exception(_:)","kind":"symbol","title":"PyException.exception(_:)","abstract":[],"role":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString":{"abstract":[],"role":"collection","title":"_PythonString","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString","url":"\/documentation\/_pythonstring","type":"topic","kind":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException":{"title":"PyException","navigatorTitle":[{"text":"PyException","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/_pythonstring\/pyexception","kind":"symbol","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PyException","kind":"identifier"}]}}}