{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/_pythonstring\/pyexception\/typeerror(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException"]]},"metadata":{"roleHeading":"Case","symbolKind":"case","modules":[{"name":"_PythonString"}],"title":"PyException.typeError(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"typeError","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","externalID":"s:13_PythonString11PyExceptionO9typeErroryACSScACmF"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/typeError(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"typeError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.swallow.documentation._PythonString/documentation/_PythonString":{"abstract":[],"role":"collection","title":"_PythonString","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString","url":"\/documentation\/_pythonstring","type":"topic","kind":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/typeError(_:)":{"title":"PyException.typeError(_:)","url":"\/documentation\/_pythonstring\/pyexception\/typeerror(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"typeError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/typeError(_:)"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException":{"title":"PyException","navigatorTitle":[{"text":"PyException","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/_pythonstring\/pyexception","kind":"symbol","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PyException","kind":"identifier"}]}}}