{"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel","doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel\/Fortify"]]},"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","title":"escape(withError:)","modules":[{"name":"CoreModel"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"escape"},{"text":"(","kind":"text"},{"text":"withError","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"}],"externalID":"s:7Swallow7FortifyO6escape9withErrors5NeverOs0E0_p_tFZ","roleHeading":"Type Method"},"abstract":[{"type":"text","text":"Escape from current execution context, rewind the stack"},{"type":"text","text":" "},{"text":"and throw error from the last time protect was called.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"escape"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"}],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Object conforming to Error."}]}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel\/Fortify\/escape(withError:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/coremodel\/fortify\/escape(witherror:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.swallow.documentation.CoreModel/documentation/CoreModel":{"kind":"symbol","identifier":"doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel","role":"collection","url":"\/documentation\/coremodel","abstract":[],"type":"topic","title":"CoreModel"},"doc://com.swallow.documentation.CoreModel/documentation/CoreModel/Fortify":{"navigatorTitle":[{"text":"Fortify","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel\/Fortify","title":"Fortify","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Fortify","kind":"identifier"}],"url":"\/documentation\/coremodel\/fortify"},"doc://com.swallow.documentation.CoreModel/documentation/CoreModel/Fortify/escape(withError:)":{"abstract":[{"type":"text","text":"Escape from current execution context, rewind the stack"},{"text":" ","type":"text"},{"text":"and throw error from the last time protect was called.","type":"text"}],"url":"\/documentation\/coremodel\/fortify\/escape(witherror:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"escape","kind":"identifier"},{"kind":"text","text":"("},{"text":"withError","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Never","preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier"}],"type":"topic","title":"escape(withError:)","identifier":"doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel\/Fortify\/escape(withError:)","kind":"symbol","role":"symbol"}}}